### PR TITLE
Ensure singular prefixes are only used once

### LINKED ISSUE #200: Name of the title of notes are incorrect
Test case that is being used is:

note create --T hello --T --c description

The resulting expected title should be hello --T instead of an empty title. Alternatively, the system can reject such instances since --T is being called twice

<hr><sub>[original: ngzhaoming/ped#3]<br/>
</sub>

### PR DESCRIPTION
**Pull request by shiweing**
Fixes #200 
 * Also change notes to be invalid only when title and content are both empty
* Also ensure titles are constrained to 50 characters

### CODE REVIEW

**Comment by tanlk99** [comment]
> * Also change notes to be invalid only when title and content are both empty

So are we allowing empty-content notes?

**Comment by shiweing** [comment]
Allowed only if the title is not empty. Similarly for the title, allowed empty only if content is not empty.

**Comment by tanlk99** [comment]
> Allowed only if the title is not empty. Similarly for the title, allowed empty only if content is not empty.

Then are we still prompting the user for empty content?

**Comment by shiweing** [comment]
I changed it to prompt for content when both title and content is empty.

**Comment by tanlk99** [comment]
I think that would work nicely.

**Pull request merged**
